### ISSUE TITLE
Can please document your project properly ? 

### ISSUE THREAD

**Issue by shravan-ks** [chaitanya11/grapesjs-plugin-publish-s3#1]
Hello, Chaitanya ..
I see that you have created a awesome feature for grape js.
I did try  to implement it but seems its not working !
can you please help out in proper way to implement?

Really appreciate  for your effort !

**Comment by chaitanya11** [comment]
Sure thing. I will be documenting it slowly, if you need anything urgent or quickly please post a question, i will answer ASAP.
