### ISSUE TITLE
Need Help with the session token.

### ISSUE THREAD

**Issue by pradeeshattlee** [chaitanya11/grapesjs-plugin-publish-s3#2]
Hello, Chaitanya...
Thanks for the effort to create an awesome feature for grapesJS.
I did try to implement it but seems it's not working properly I am stuck with the session token can you please direct on how to obtain the session token.

It would really be helpful if you could give a Documentation walkthrough to achieve publishing the rendered HTML. 

I really appreciate your effort!

**Comment by chaitanya11** [comment]
@pradeeshattlee i have implemented obtaining sts credentials and publishing html in https://github.com/chaitanya11/BodylessCMS project please have a look at code from that project.

**Comment by pradeeshattlee** [comment]
Thanks for the response Chaitanya,
I am new to angular.

I tried to clone  https://github.com/chaitanya11/BodylessCMS this repository and running application in local as in the documentation but an error was generated.

**Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.**
![image](https://user-images.githubusercontent.com/25820475/69867747-bdcac680-12cd-11ea-95d9-1f689844784a.png)

I tried to install @angular/compiler-cli and typescript and cleared the old node modules and package-lock and some other errors was also satisfied then hit **npm install** again the previous error was cleared but the new error was generated 
**ERROR in ./src/main.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (C:\nodejs\BodylessCMS\node_modules\@ngtools\webpack\src\loader.js:33:15)
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./src/polyfills.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (C:\nodejs\BodylessCMS\node_modules\@ngtools\webpack\src\loader.js:33:15)
 @ multi ./src/polyfills.ts
ERROR in multi ./src/styles.css
Module not found: Error: Can't resolve 'C:\nodejs\BodylessCMS\src\styles.css' in 'C:\nodejs\BodylessCMS\node_modules\@angular\cli\models\webpack-configs'
resolve 'C:\nodejs\BodylessCMS\src\styles.css' in 'C:\nodejs\BodylessCMS\node_modules\@angular\cli\models\webpack-configs'
  using description file: C:\nodejs\BodylessCMS\node_modules\@angular\cli\package.json (relative path: ./models/webpack-configs)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\nodejs\BodylessCMS\node_modules\@angular\cli\package.json (relative path: ./models/webpack-configs)
    using description file: C:\nodejs\BodylessCMS\package.json (relative path: ./src/styles.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\nodejs\BodylessCMS\src\styles.css doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\nodejs\BodylessCMS\src\styles.css.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\nodejs\BodylessCMS\src\styles.css.js doesn't exist
      as directory
        C:\nodejs\BodylessCMS\src\styles.css doesn't exist
[C:\nodejs\BodylessCMS\src\styles.css]
[C:\nodejs\BodylessCMS\src\styles.css.ts]
[C:\nodejs\BodylessCMS\src\styles.css.js]
[C:\nodejs\BodylessCMS\src\styles.css]
 @ multi ./src/styles.css
ERROR in Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (C:\nodejs\BodylessCMS\node_modules\@angular\compiler\bundles\compiler.umd.js:11967:27)
    at CompileMetadataResolver.getNgModuleMetadata (C:\nodejs\BodylessCMS\node_modules\@angular\compiler\bundles\compiler.umd.js:10609:47)
    at visitLazyRoute (C:\nodejs\BodylessCMS\node_modules\@angular\compiler\bundles\compiler.umd.js:21844:72)
    at AotCompiler.listLazyRoutes (C:\nodejs\BodylessCMS\node_modules\@angular\compiler\bundles\compiler.umd.js:21799:24)
    at AngularCompilerProgram.listLazyRoutes (C:\nodejs\BodylessCMS\node_modules\@angular\compiler-cli\src\transformers\program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\nodejs\BodylessCMS\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\nodejs\BodylessCMS\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:246:66)
    at Promise.resolve.then.then (C:\nodejs\BodylessCMS\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:537:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)**
![image](https://user-images.githubusercontent.com/25820475/69867953-6416cc00-12ce-11ea-99ab-53d7ebf0ebd4.png)

Can You please help me out on this.

Thanks in advance....!

**Comment by pradeeshattlee** [comment]
Hi @chaitanya11  
Any Solution For the above-mentioned error.

Please have a look at the issue and provide a solution 

It would be a great help.
Thanks,

**Comment by chaitanya11** [comment]
@pradeeshattlee  i have updated the angular version in [BodylessCMS](https://github.com/chaitanya11/BodylessCMS), you can give try now. To generate temporary credentials please flow the readme file in the same repo.
